### ISSUE TITLE
Unable to Move Window

### ISSUE THREAD

**Issue by josh-justjosh** [PrashantMohta/mlcd#1]
At the moment, it isn't currently possible to move the Mock LCD without any programs crashing.
Not sure if this an issue with the way you've designed the code or with the pygame base

**Comment by PrashantMohta** [comment]
thanks for bringing this to my notice! it's a pygame thing, you have to create a game loop and process it's events for the window to be movable, have updated the mlcd_example.py to reflect the changes.
